#!/bin/bash
#
# This script automates the process of changing a PeopleSoft access password (e.g., for SYSADM)
# using a PeopleTools Data Mover script.
#
# It securely prompts for credentials and ensures that no passwords are stored in plaintext
# in files or command-line history.
#

# --- Configuration ---
# IMPORTANT: Update these variables to match your environment.
PS_HOME="/opt/oracle/psft/pt" # Path to PeopleTools installation
ACCESS_ID="SYSADM"             # The PeopleSoft Access ID to update
DB_NAME="PSEMU"                # The database name
DB_TYPE="ORACLE"               # The database type

echo "PeopleSoft Password Change Automation Script"
echo "------------------------------------------"
echo

# --- Securely Prompt for Credentials ---

# 1. Get the credentials for the user running the Data Mover script.
# This user must have privileges to update the PSACCESSPROFILE table.
echo "Please enter the database credentials for running Data Mover."
read -p "Database User ID: " DM_USER
read -s -p "Database Password: " DM_PASSWORD
echo
echo

# 2. Get the new password for the PeopleSoft Access ID.
echo "Please enter the new password for the Access ID: ${ACCESS_ID}"
read -s -p "New Password: " NEW_PASSWORD
echo
read -s -p "Confirm New Password: " NEW_PASSWORD_CONFIRM
echo
echo

# --- Validate Input ---
if [ -z "$DM_USER" ] || [ -z "$DM_PASSWORD" ] || [ -z "$NEW_PASSWORD" ]; then
    echo "Error: All user IDs and passwords are required." >&2
    exit 1
fi

if [ "$NEW_PASSWORD" != "$NEW_PASSWORD_CONFIRM" ]; then
    echo "Error: The new passwords do not match." >&2
    exit 1
fi

echo "Input validation successful. Preparing to run Data Mover..."
echo

# --- Create a temporary Data Mover Script ---
# Using mktemp to create a secure temporary file
DMS_FILE=$(mktemp /tmp/change_password.XXXXXX.dms)
if [ ! -f "$DMS_FILE" ]; then
    echo "Error: Could not create temporary file." >&2
    exit 1
fi

echo "Generating Data Mover script at: ${DMS_FILE}"

# Here document (cat << EOF) is used to write the multi-line DMS script.
# IMPORTANT: The ENCRYPT_PASSWORD command works on the *next* password processed by Data Mover.
# We pass the new password directly in the script content. This is safe because the file
# will be deleted immediately after execution.
cat > "$DMS_FILE" << EOF
-- Generated by change_peoplesoft_password.sh on $(date)
SET LOG ${DMS_FILE}.log;
SET NO TRACE;

ENCRYPT_PASSWORD ${NEW_PASSWORD};

UPDATE PSACCESSPROFILE
   SET ACCESSPSWD = :ACCESSPSWD
 WHERE ACCESSID = '${ACCESS_ID}';

COMMIT;
EOF

echo "Data Mover script generated successfully."
echo

# --- Execute Data Mover ---
# The PSSWD environment variable is used by PeopleSoft command-line utilities
# to securely provide a password without putting it on the command line.
export PSSWD=$DM_PASSWORD

# Define the path to the Data Mover executable
PS_CMD="${PS_HOME}/bin/psdmt"

if [ ! -x "$PS_CMD" ]; then
    echo "Error: Data Mover executable not found or not executable at: ${PS_CMD}" >&2
    # Clean up before exiting
    unset PSSWD
    rm -f "$DMS_FILE"
    exit 1
fi

echo "Running Data Mover..."
# The -CI flag tells the utility to use the User ID from the command line (-CO)
# and the password from the PSSWD environment variable.
"$PS_CMD" -CT $DB_TYPE -CD $DB_NAME -CO $DM_USER -CI -I "$DMS_FILE"

# Store the exit code for later
EXIT_CODE=$?

# --- Cleanup ---
# Immediately unset the password variable and remove the temporary script
unset PSSWD
rm -f "$DMS_FILE"

echo "Cleanup complete."
echo

# --- Final Status ---
if [ $EXIT_CODE -eq 0 ]; then
    echo "Password change successful for Access ID: ${ACCESS_ID}"
    echo "Please check the log file for details: ${DMS_FILE}.log"
else
    echo "Error: Data Mover process failed with exit code ${EXIT_CODE}." >&2
    echo "Please check the log file for errors: ${DMS_FILE}.log" >&2
    exit 1
fi

exit 0
